export const SAVE_ARTICLE = 'SAVE_ARTICLE';
export const PUBLIC_ARTICLE = 'PUBLIC_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const SET_ARTICLE = 'SET_ARTICLE';
export const UPDATE_COVER_IMAGE = 'UPDATE_COVER_IMAGE';
