export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
